### ISSUE TITLE
请问有办法取得个人和群的唯一标识吗？或者有没有办法自己构建？

### ISSUE THREAD

**Issue by jerryge** [wechaty/wechaty#133]
如题，应用场景比如需要保存聊天记录。

**Comment by zixia** [comment]
You can get the unique ID for a contact/room by `contact.id` and `room.id`. However, this `id` will not keep consistent across Web Sessions.

If you want to identify the same contact across web sessions, you need to set a remark for the contact, like: `contact.remark('1')`, then you can expect to get `1` for the same contact by call `contact.remark()`.

For a room, I still have no idea of how to identify it right now, because web wechat has no "remark for the room" feature yet. If anyone has any good idea or suggestion, please let me know, will appreciated it.

One more thing, there's looks have a way to get the Uin for a contact & a room from this issue: https://github.com/wechaty/wechaty/issues/90 . But we still did not have time to figure out how it works. If you could help us to figure it out, we can add this feature to Wechaty.

**Comment by jerryge** [comment]
It is great! Thank you very much!

**Comment by zixia** [comment]
### Wechaty v0.15 Can Get the Unique ID of Contact/Room across sessions by PuppetPadchat

Start from Wechaty v0.15, we enable new Puppet System with all protocols support, include but not limited to Android, iOS, Pad, Win32, Web.

Learn more at:

* Wechaty v0.15 Alpha Testing - https://github.com/Chatie/wechaty/issues/1296
* PuppetPadchat - https://github.com/lijiarui/wechaty-puppet-padchat

**Comment by ZohnnyCode** [comment]
remark()设置的备注, 在下次登录的时候也会失效, 不行呢, 请问现在有别的解决方法吗?
