### ISSUE TITLE
Doesn't work with UK Android account/device

### ISSUE THREAD

**Issue by timdonovanuk** [wechaty/wechaty#1556]
Hi,

I tried the starter-bot.js. When I scan the QR code that starter-bot generates, I get the below error on my phone. I'm totally new to WeChat and not really sure whats going on here. If I click "Update Now" it takes me to the Apple App store....I'm on an Android device.

![image](https://user-images.githubusercontent.com/8156439/44221476-8e945280-a179-11e8-939a-36612ed41933.png)

**Comment by zixia** [comment]
Interesting... it seems that your android phone does not display right, and I can not believe that "Update Now" will take you to the Apple Store...

And, there's another question: we did not have `starter-bot.js` in this repository.

So please provide all the required information by following the ISSUE Template, or we can not be able to help, thanks.

**Comment by timdonovanuk** [comment]
You're right, it was from https://github.com/Chatie/wechaty-getting-started not this repo.

**Comment by zixia** [comment]
Yes, but the getting-started repo should be ok because many users had start from there.

I'd like suggest you to join our Developer Communitte Wechat Group, there's many developers over there, and you can ask to see if there's anyone can help you with this strange error.

You can find the QR Code at the README in this repo.
