### ISSUE TITLE
Room.findAll() can only return a few rooms, not all of them which displayed on my phone 

### ISSUE THREAD

**Issue by zhaoPengInGithub** [wechaty/wechaty#1648]
I've tried many times,including setTimeout for 6000ms,still not working, is there something wrong with what I did?
```js
function onLogin (user) {
  console.log(`${user} login`);
  setTimeout(async function(){
    const roomList =await bot.Room.findAll();
    console.log(roomList);
  },6000);
}
```

**Comment by lijiarui** [comment]
Which puppet are you using?

**Comment by esmiles** [comment]
I also meet this issue with wx web api.

**Comment by lijiarui** [comment]
Close this issue since long time no response

**Comment by huan** [comment]
This is a very typical question when a developer are using Wechaty, we should answer this question before close it.

P.S. it is unrelated to any specific puppet: all puppet will experiencing the same problem(`Room.findAll()` can not garantee returning all rooms) due to the limitation of the Wechat behaviour.

**Comment by su-chang** [comment]
When we login Wechaty by different protocals (`web` / `ipad` / `mac`) at first time, we can not load all rooms of the bot which we could find in WeChat App.

We could only load some active rooms or some rooms which added to Contacts in WeChat.

Different protocal has different rules. But the same rule is that we could get the room which has message(_system message or public message_) coming. So if one room without message coming, we can load this room hardly.
