### ISSUE TITLE
Wechaty v0.23 PadPro Testing, an enhanced pad puppet implementation! 

### ISSUE THREAD

**Issue by windmemory** [wechaty/wechaty#1668]
Hello to developers who are using Wechaty,

We have excellent news for you: Wechaty New Puppet System is going to ready for testing!, and Alpha Testing Volunteers are open to applications now.

We have launched a new puppet `wechaty-puppet-padpro` few weeks ago, now we are launching alpha test for `wechaty-puppet-padpro`.

New puppet `wechaty-puppet-padpro` is the new version of `wechaty-puppet-padchat` which solves some problems from architecture level. Comparing with `wechaty-puppet-padchat`, the new puppet has improvement in some aspects below:

* Able to get the weixin id with `Contact.weixin()` function for those who set a custom weixin id for themselves
* Send and receive 60s voice 
* Send and receive large images
* Room announcement feature

Below is some difference between `wechaty-puppet-padchat` and `wechaty-puppet-padpro`

* `wechaty-puppet-padpro` establishes connection with Wechat server from client side
* Auto reconnect data stored in cloud, each token has its own storage for the auth data

Start from today; we need some volunteers who are interested in joining the alpha testing. If you are one of them, please leave a comments under this issue, introduce yourself about who you are and what you want to do(please DO follow the following TEMPLATE and fill it in details, or you might not be able to be selected), so that we can be able to add you to the alpha testers list if you are qualified.

If you want to benefit from all the new features, and cannot wait for the next v0.24 release, then you are welcomed to apply for joining the v0.23 Alpha Tester List!

#### Install

```shell
npm install wechaty
npm install wechaty-puppet-padpro
```

#### Example

```ts

import { Wechaty } from 'wechaty'

const WECHATY_PUPPET_PADPRO_TOKEN = 'your-token-here'

const puppet = 'wechaty-puppet-padpro' // 使用ipad 的方式接入。

const puppetOptions = {
  token: WECHATY_PUPPET_PADPRO_TOKEN,
}

const bot = new Wechaty({
  puppet,
  puppetOptions,
})

// 设置完成

// 运行 wechaty
bot
.on('scan', (qrcode, status) => console.log(`Scan QR Code to login: ${status}\nhttps://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(qrcode)}`))
.on('login',            user => console.log(`User ${user} logined`))
.on('message',       message => console.log(`Message: ${message}`))
.start()
```

see more: https://github.com/botorange/wechaty-puppet-padpro
contact: 
![](https://github.com/botorange/wechaty-puppet-padpro/raw/master/image/contact.gif)

### Wechaty Puppet Padpro Alpha Tester Apply Template
---
#### 3. Are Your Bot Related with the Following Tasks? (YES/NO)
* Gambling
* Adault & Sex

**Comment by xuanmiao-zero** [comment]
1. Introduce Yourself(who you are): JS developer
2. Explain the Problem You Want to Solve:(what you do): research WeChat robotics solutions
3. Are Your Bot Related with the Following Tasks? (YES/NO) NO
  * Gambling
  * Adault & Sex
4. Your Email: xuanmiaozero@gmail.com
5. Your Wechat: only-love-xuanmiao
6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from [README.md](https://github.com/Chatie/wechaty/blob/master/README.md): (Please join the group if you are not, and then say YES at here) YES
7. I understand that the `wechaty-puppet-padpro` is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here) YES 轩邈

**Comment by huangyanyang** [comment]
#### 1. Introduce Yourself(who you are):黄燕羊
#### 2. Explain the Problem You Want to Solve:(what you do):我想一键加群好友
#### 3. Are Your Bot Related with the Following Tasks? (YES/NO)
* Gambling
* Adault & Sex
NO
#### 4. Your Email: 930256283@qq.com
#### 5. Your Wechat: hyy18320055362
#### 6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from [README.md](https://github.com/Chatie/wechaty/blob/master/README.md): (Please join the group if you are not, and then say YES at here)YES
#### 7. I understand that the `wechaty-puppet-padpro` is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)YES黄燕羊

**Comment by zhaizong** [comment]
@xuanmiao-zero @huangyanyang Your applications are approved. Please check your email inbox for the next steps.

Welcome!

**Comment by shijunti19** [comment]
1. Introduce Yourself(who you are):JS developer
2. Explain the Problem You Want to Solve:(what you do):我想微信提示
3. Are Your Bot Related with the Following Tasks? (YES/NO)
Gambling
Adault & Sex
NO
4. Your Email: 527528007@qq.com
5. Your Wechat: shijunti19
6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here)YES
7. I understand that the wechaty-puppet-padpro is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)YES陆忠

**Comment by gengchen528** [comment]
1. Introduce Yourself(who you are): JS and node developer
2. Explain the Problem You Want to Solve:(what you do):  自动拉群及语音发送功能
3. Are Your Bot Related with the Following Tasks? (YES/NO) NO
Gambling
Adault & Sex
4. Your Email: 478914121@qq.com
5. Your Wechat: CG12104410
6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: (Please join the group if you are not, and then say YES at here) YES
7. I understand that the wechaty-puppet-padpro is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)YES  Leo_chen

**Comment by zhaizong** [comment]
@shijunti19 @gengchen528 Your applications are approved. Please check your email inbox for the next steps.

Welcome!

**Comment by gengchen528** [comment]
> @shijunti19 @gengchen528 Your applications are approved. Please check your email inbox for the next steps.
> 
> Welcome!

thank you

**Comment by heng19970427** [comment]
1. Introduce Yourself(who you are): python,java developer
2. Explain the Problem You Want to Solve:(what you do):1,获取所有标签;2,给好友设置标签;3,根据标签获取该标签下的好友
3. Are Your Bot Related with the Following Tasks? (YES/NO)NO
Gambling
Adault & Sex
4. Your Email:xiaoliu@gmail.com
5. Your Wechat:LW52071
6. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from README.md: YES
7. I understand that the wechaty-puppet-padpro is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: YES,xiaoliu

**Comment by shmilyoo** [comment]
#### 1\. Introduce Yourself(who you are):
js developer

#### 2\. Explain the Problem You Want to Solve:(what you do):
help me to manage private group and do some reminder affair

#### 3\. Are Your Bot Related with the Following Tasks? (YES/NO)

*   Gambling
*   Adault & Sex
NO

#### 4\. Your Email:
fighter_yy@qq.com

#### 5\. Your Wechat:
yyxyygp

#### 6\. I Had Joined the Wechaty Developers' Home Wechat Room by Scan QRCode from [README.md](https://github.com/Chatie/wechaty/blob/master/README.md): (Please join the group if you are not, and then say YES at here)
YES

#### 7\. I understand that the `wechaty-puppet-padpro` is in very Early Alpha Stage, and I have the necessary engineering technics to deal with the bugs instead of just asking for support: (Please say YES, then followed by your Name at here)
YES
Andrew Ye

**Comment by lijiarui** [comment]
Hi all
Please contact the following wechat to get the testing token, no need to 

contact: 
![](https://github.com/botorange/wechaty-puppet-padpro/raw/master/image/contact.gif)
