### ISSUE TITLE
Message对象的mention和mentionSelf异步函数无效

### ISSUE THREAD

**Issue by BeanHsiang** [wechaty/wechaty#1698]
### 操作步骤

0. 克隆最新的项目，打开\examples\professional\tuling123-bot.js
1. 在onMessage函数体的开头添加代码：

```javascript
async function onMessage(msg) {
  // reply from special room
  const room = msg.room();
  const topic = await room.topic();

  if (room) {
    // console.log(msg.room());
    console.log('start onMessage');
    // result = await msg.mentionSelf();
    result = await msg.mention();
    console.log(result);
   }
  // Skip message from self, or inside a room
  if (msg.self() || msg.room() || msg.from().name() === '微信团队' || msg.type() !== Message.Type.Text) return

  console.log('Bot', 'talk: %s', msg.text())

  try {
    const { text: reply } = await tuling.ask(msg.text(), { userid: msg.from() })
    console.log('Tuling123', 'Talker reply:"%s" for "%s" ',
      reply,
      msg.text(),
    )
    await msg.say(reply)
  } catch (e) {
    console.error('Bot', 'on message tuling.ask() exception: %s', e && e.message || e)
  }
}
```

2. 执行代码，扫码登录一个bot，用另一个微信号在手机端登录，并在微信群中@前面登录的bot。 

### 期望结果

在打印result时有非空的对象，换成mentionSelf时，期望打印true

### 实际打印结果

```
start onMessage
[]
```

换成mentionSelf时
```
start onMessage
false
```

**Comment by lijiarui** [comment]
Which puppet are you using?

**Comment by seanxlliu** [comment]
I am using the default puppet `Wechaty.instance()`. Got the same behavior. The message shows '@' but it was just plaint-text.

**Comment by lijiarui** [comment]
Please follow the issue template, and we will dig into it. Thanks!

> Important：Please file the issue follow the template, or we won't help you to solve the problem.


## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer:

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer:

- What is your node version? (run `node --version`)
Answer:

- What os are you using
Answer:

## 2. Describe the bug
Give a clear and concise description of what the bug is.

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

Steps to reproduce the behavior:
1. run '...'
2. ...
3. ...

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.


## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context
Add any other context about the problem here.

[bug]
