### ISSUE TITLE
无论是否为好友 ，都提示has been friend with bot, no need to send friend request!

### ISSUE THREAD

**Issue by renwfy** [wechaty/wechaty#1778]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://docs.chatie.io/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer: 0.22.6

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: padpro

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: padpro": "0.0.57"

- What is your node version? (run `node --version`)
Answer: v10.15.3

- What os are you using
Answer: mac

## 2. Describe the bug
测试场景是添加群成员
无论是否为好友   Friendship.add(contact, hello) 都提示：
 WARN PuppetPadpro friendshipAdd wxid_hshg4vdh0ix421 has been friend with bot, no need to send friend request!

## 3. To Reproduce
const memberList = await room.memberAll()
for (let i = 0; i < memberList.length; i++) {
  await bot.Friendship.add(member, '你好')
}

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
![image](https://user-images.githubusercontent.com/6526280/57665575-f4413c80-762e-11e9-932d-6a38854a0fec.png)

## 7. Additional context

[bug]

**Comment by windmemory** [comment]
Don't put screenshot image as the output logs, just copy paste the log into the issue. 

You should check whether the user is oneway friend with the bot. 

In WeChat, friendship are double directions.

For example: Bot and Tom are friends means that Bot is Tom's friend and Tom is Bot's friend. When you delete Bot in Tom's account, you are removing the connection from Tom to Bot, but the connection from Bot to Tom is still there. When you try to accept the request from Bot, it can not be done since Bot is already a friend of Tom.

**Comment by renwfy** [comment]
双方一直不是好友，是一个完全不认识的，他们从来没有加个好友
也会提示：WARN PuppetPadpro friendshipAdd wxid_y85hr471 has been friend with bot, no need to send friend request!

**Comment by renwfy** [comment]
更新了版本 ：
"wechaty": "^0.26.1",
 "wechaty-puppet-padpro": "^0.2.1"

没有报错了，但是没有成功发送加好友请求
