### ISSUE TITLE
We need FriendShip.add() or some new method to get  raw payload

### ISSUE THREAD

**Issue by CooperFu** [wechaty/wechaty#1849]
**Is your feature request related to a problem? Please describe.**

We are [Uniqueway](http://www.uniqueway.com). we already hook the interface about FriendShip.add() to get rawPayload through Wechaty and WechatyPadPro.

Cause our situation is very complicated, we bought 23 keys to realize the function of actively adding friends. (Every number adds 6 friends every day) But because I recently encountered a problem that padpro can't log in. We need to switch to WechatyMacPro.

We have our own interface for each update. Change the files of the three repos(Wechaty, WechatyPuppet, WechatyPadPro) and publish them yourself. Get the guest's original payload with the `bot.friendShip.add()` method. Very troublesome.

**Describe the solution you'd like**

So I want to be able to provide this interface officially. But to avoid abuse, it can be like `bot.Contact.load()`. Not written on the document. As an internal method. For example, `bot.friendShip.dirtyAdd()` returns `rawPayload`

[enhancement]

**Comment by huan** [comment]
I'd like to flag it as a question, and if there's enough attention/discussion on this problem, then I'll take time to think about it.

**Comment by huan** [comment]
I'll close this issue because it is inactive for more than 3 months.

BTW: there's many workarounds to archive this goal.

For example, you can always call the puppet provider implementation by visiting `wechaty.puppet`, and as the `wechaty-puppet` has all the methods that you need, so you can call the `wechaty.puppet.friendshipRawPayload(id)` to get the `FriendshipRawPayload` to fulfill your needs.

For example, the following code will demonstrate this workaround. I hope this will help you guys some.

```ts
const bot = new Wechaty()
// after the bot get logged in...
const rawPayload = await (bot.puppet as any).contactRawPayload(bot.id)
console.info('self raw payload:', rawPayload)
```

All methods (including the private ones) will be able to be used like this, which including the `bot.puppet.friendshipRawPayload()` method.
