### ISSUE TITLE
Question about wechaty next version

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#1932]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]
The latest version of `wechaty` is still at 0.32.5, but the next version is 0.37.x, I'm curious about it.

So does `wechaty-puppet`, both of them skip one or two latest version.

**Comment by huan** [comment]
Yes. That's because we have too many breaking changes introduced by the heavy development, and when we have breaking changes, we will bump the minor version so that we can make sure our module version is strict following the SemVer semantic.

The user should always stick on the `@latest` version and should not care about the `@next` version.

We will publish a stable version to update the `@latest` when we are ready.

**Comment by windmemory** [comment]
@huan What can we do to make us ready? Anything still WIP?

**Comment by su-chang** [comment]
@huan 
I want to bump the wechaty version to `0.34.0` now. But I found some breaking changes relate to the emit event both in `0.35` and `0.37` version.

e.g. `heartbeat` event update in `0.37`.

Which version should I rebase for the new version? Or some other suggestions?

BTW, is there some rules for new latest version? I can not  find tag `v0.32`.

**Comment by huan** [comment]
I'd like to suggest that we should have version 0.38 as our stable version because current version is 37.

There's no special rules for the latest version number, just bump the minor number to even sound be enough.

**Comment by su-chang** [comment]
Understand.

Thanks for your suggestion.

**Comment by huan** [comment]
BTW: please also remember to bump the wechaty-puppet to an even minor version so that we can have both Wechaty and the puppet with the production version.

**Comment by huan** [comment]
Please kindly close this issue if your question has been answered, thank you very much.
