### ISSUE TITLE
为什么 padplus 的 on message 监听不到公众号的消息

### ISSUE THREAD

**Issue by yibai567** [wechaty/wechaty#1938]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/wechaty

[question]

**Comment by su-chang** [comment]
Which puppet are you using now? `wechaty-puppet-puppeteer` or `wechaty-puppet-padplus`?

**Comment by WenHou** [comment]
wechaty-puppet-padplus

**Comment by su-chang** [comment]
Sorry, it does not support receive OA message.

**Comment by WenHou** [comment]
有什么其他办法吗，求助

**Comment by su-chang** [comment]
Sorry, it does not support.

**Comment by huan** [comment]
@su-chang I'd like to put some additional information on this topic because I believe there have some ways to fulfill this requirement.

@WenHou There will be a new puppet supports PC Windows protocol recently which can be send and receive Official Account message without any problem.

Please stay tuned.

**Comment by WenHou** [comment]
👍，期待，加油ヾ(◍°∇°◍)ﾉﾞ

**Comment by huan** [comment]
@WenHou See #1941
