### ISSUE TITLE
the relationship between hostie, grpc and puppet.

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/wechaty#1947]
There are many concepts that confuses me when we get deep into wechaty . I will explain my understanding, which I can't sure.

* **First**, there are many puppet protocols under chatie server. But `python-wechaty`/`go-wechaty` don't need to care about the detail.
* **Second**, grpc is used in `python-wechaty-puppet` module, which handle the connection between the `wechaty` client and `chatie-host` server. 
* **Third**, `wechaty-puppet` and `wechaty-puppet-padplus` is different, this is where I get most confused. For example, `wechaty-puppet` is used in `python-wechaty`, which use `grpc` to connect `chatie-grpc`. `wechaty-puppet-padplus` implement `padplus` protocol to handle wechat information operation.  `wechaty-puppet` and `wechaty-puppet-padplus` are isolated with `chatie-grpc`.

**Comment by dingdayu** [comment]
I have a picture, I wonder if I can help you.

![未命名文件](https://user-images.githubusercontent.com/2040348/79714525-b1d6b400-8303-11ea-904f-2cd58e9d77fb.png)

Please @huan  verify.

**Comment by huan** [comment]
@dingdayu Only part of your picture is right. Please see my diagram at https://github.com/wechaty/go-wechaty/issues/22#issuecomment-612992099 to see the right structure.

To answer questions from @wj-Mcat :

> * **First**, there are many puppet protocols under the chatie server. But `python-wechaty`/`go-wechaty` don't need to care about the detail.

Yes, you are absolutely right.

We will never need to care about the puppet protocols in `python-wechaty` or `go-wechaty` anymore.

What we need to do is to implement the `wechaty-puppet` interface and connect all the API to the GRPC service. ([chatie-grpc](https://pypi.org/project/chatie-grpc/) in python, and [github.com/wechaty/go-grpc](https://github.com/wechaty/go-grpc) in Go)

> * **Second**, grpc is used in `python-wechaty-puppet` module, which handle the connection between the `wechaty` client and `chatie-host` server. 

Yes, you are right.

And as I mentioned in the previous answer, the grpc module for Python we have already published at [chatie-grpc](https://pypi.org/project/chatie-grpc/)

> * **Third**, `wechaty-puppet` and `wechaty-puppet-padplus` is different, this is where I get most confused. For example, `wechaty-puppet` is used in `python-wechaty`, which use `grpc` to connect `chatie-grpc`. `wechaty-puppet-padplus` implement `padplus` protocol to handle wechat information operation.  `wechaty-puppet` and `wechaty-puppet-padplus` are isolated with `chatie-grpc`. 

What you have described in your question are mostly not wrong.

> `wechaty-puppet` and `wechaty-puppet-padplus` is different

You should never care about the `wechaty-puppet-padplus` in our Python Wechaty. 

What you need to design is the `wechaty-puppet` and the `wechaty-puppet-hostie`, and we will mostly only deal with those two puppet modules in the future.

>  `wechaty-puppet` is used in `python-wechaty`, which use `grpc` to connect `chatie-grpc`. 

Not wrong. If we describe it more precisely: the `wechaty-puppet-hostie` implements the abstraction of `wechaty-puppet`, and the `wechaty-puppet-hostie` will use `chatie-grpc` PyPI module to connect with our GRPC service.

>  `wechaty-puppet-padplus` implement `padplus` protocol to handle wechat information operation. 

This is also right.

However, we do not need to care about them because they are unrelated to our Python Wechaty.

Python Wechaty will use `wechaty-puppet-hostie`, and it will connect to the GRPC service.

Both the `wechaty-puppet-padplus` and the `padplus` protocol are behind the GRPC service, which means we can ignore them safely for now.

> `wechaty-puppet` and `wechaty-puppet-padplus` are isolated with `chatie-grpc`. 

The above sentence is the only wrong one in all your questions.

In TypeScript: `wechaty-puppet-padplus` is a child class (PuppetPadplus) that inherit the `wechaty-puppet` abstraction class (Puppet), and it implemented all the requirements from the parent class `Puppet` in order to satisfied Wechaty.

In Python: `wechaty-puppet-hostie`(in Python) and `wechaty-puppet-padplus`(in TypeScript) are isolated with `chatie-grpc`.

-----

At last, please see my diagram at https://github.com/wechaty/go-wechaty/issues/22#issuecomment-612992099 to see the big picture of the relationship between `wechaty-puppet`, `wechaty-puppet-hostie`, and `wechaty-puppet-XXX`.

Thank you for asking the above questions, I hope my answer can help you to make it clear about the Wechaty Architecture Design.

Please feel free to let me know if you have more questions, Cheers!
