### ISSUE TITLE
we should create a "wechaty/awesome-wechaty" repository

### ISSUE THREAD

**Issue by JesseWeb** [wechaty/wechaty#1965]
This repository is used to remind users of everything related to wechaty, including project, code, plugin, middleware, etc

should be discuss.

**Comment by huan** [comment]
I agree that it would be great for the users to have a big map of all the great wechaty ecosystem related projects, documents, blogs, videos, etc.

Please feel free to create it under your account and show what it should look like so that we can continue discussing it furthermore!

I believe we can create it officially after it got more than 5 people from our contributors who vote +1 to it. (any suggestion would be welcome)
