### ISSUE TITLE
How to control the wechaty status by myself?

### ISSUE THREAD

**Issue by sunshinearea** [wechaty/wechaty#1972]
After I deployed the service to the server, I started the WeChaty login program. I found that if the connection of WeChaty was dropped during the operation, the login operation would be automatically performed. Meanwhile, I also wanted to control the login, logout or stop operation of the service during the operation, so I called the start(), logout() and stop() functions in the API.

Bot Puppet：padplus（0.6.1）

1. When WeChaty is in the login state, I call stop (), which shows that WeChaty is logged out, but after a while, WeChaty will automatically log in and succeed.
2. When I call logout(), WeChat will logout, but after a while, the program will automatically call the qr code scanning method, prompting me to scan and log in. At this time, if I debug this service in another computer on Mac OS, the service will keep reporting errors
Is there anything wrong with my operation? How do you automatically control login, logout, or stop?

**Comment by su-chang** [comment]
> 2\. At this time, if I debug this service in another computer on Mac OS, the service will keep reporting errors

One server keep running, and then use the same `token` in other server, it not be permitted.

BTW, If you want do some test, you must exit the prod server, or get another token for test server.

**wechaty.stop()**
Stop all listener of wechaty and release cache but will not logout WeChat. So that you can `wechaty.start()` next time without scan QR Code for login.

**wechaty.logout()**
Logout WeChat and call QR Code scanning.

Both method will not stop your token unless you exit your node process.

**Comment by sunshinearea** [comment]
I understand that a token supports a WeChaty login service, and if the WeChaty on my service is logged out, will it not run on the other side as well? If I want to run the same token program, I must stop the previous service?

**Comment by su-chang** [comment]
Yes, because of request QR Code also need token.

**Comment by sunshinearea** [comment]
I got it,Thanks.

**Comment by sunshinearea** [comment]
@su-chang  I have another question, if I destroy the wechaty object running in the service, can I stop the service
