### ISSUE TITLE
Using your Puppet PadPlus token with Python, Java, and Go Wechaty

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#1985]
Since we have our branding new Multi-lang Wechaty ready to use from this week, it would be great for our Python, Java, and Go developers to have a try with them!

1. https://github.com/wechaty/python-wechaty-getting-started
1. https://github.com/wechaty/java-wechaty-getting-started
1. https://github.com/wechaty/go-wechaty-getting-started

However, all of the above gettings started repos need a TOKEN for [wechaty-puppet-hostie](https://github.com/wechaty/wechaty-puppet-hostie).

A token for [wechaty-puppet-padplus](https://github.com/wechaty/wechaty-puppet-padplus/) will not work for our MultiLang Wechaty unless you do a converting as described below:

### 1 Pull the latest Wechaty Docker Image

```sh
docker pull wechaty/wechaty
```

### 2 Set your padplus token

```sh
# Set your padplus token which you want to use by hostie
export WECHATY_PUPPET_PADPLUS_TOKEN=puppet_padplus_333333333333333
```

### 3 Start your Wechaty Token Gate Server:

Notice: 

1. The server IP must be public on the internet, and 
1. the `WECHATY_HOSTIE_PORT` must be accessible on the internet.

```sh
# Set port for your hostie service: must be published accessible on the internet
export WECHATY_HOSTIE_PORT=8788

export WECHATY_PUPPET=wechaty-puppet-padplus
export WECHATY_LOG=verbose

docker run \
  --rm \
  -ti \
  -e WECHATY_LOG \
  -e WECHATY_PUPPET \
  -e WECHATY_PUPPET_PADPLUS_TOKEN \
  -e WECHATY_HOSTIE_PORT \
  -e WECHATY_TOKEN="$WECHATY_PUPPET_PADPLUS_TOKEN" \
  -p "$WECHATY_HOSTIE_PORT:$WECHATY_HOSTIE_PORT" \
  wechaty/wechaty
```

### 4 That's it, you are set!

Your PadPlus token is ready to use by Python, Java, and Go Wechaty!

Link to: #1927

## All in One Command

For use Wechaty Token Gateway with ease, you can copy/paste the following code in your bash shell:

```sh
function wechaty_token_gateway_padplus () {
  if [ -z "$1" ]; then
    >&2 echo -e "Missing argument.\nUsage: $0 <padplus_token>"
    exit 1
  fi

  WECHATY_PUPPET_PADPLUS_TOKEN=$1
  WECHATY_PUPPET=wechaty-puppet-padplus

  # Set port for your hostie service: must be published accessible on the internet
  WECHATY_HOSTIE_PORT=8788

  docker pull wechaty/wechaty
  
  docker run \
  --rm \
  -ti \
  -e WECHATY_LOG \
  -e WECHATY_PUPPET \
  -e WECHATY_PUPPET_PADPLUS_TOKEN \
  -e WECHATY_HOSTIE_PORT \
  -e WECHATY_TOKEN="$WECHATY_PUPPET_PADPLUS_TOKEN" \
  -p "$WECHATY_HOSTIE_PORT" \
  wechaty/wechaty
}
```

Then you will be able to start your Wechaty Token Gateway with just one line of command:

```sh
wechaty_token_gateway_padplus puppet_padplus_token_xxx
```

I hope you enjoy it!

## Update Aug 13, 2020: docker image name changed

Please notice that our docker image has been renamed to **wechaty/wechaty**.

The ~~`zixia/wechaty`~~ will not be updated anymore, so please remember to rewrite your scripts to use the **wechaty/wechaty** image.

- Before: `zixia/wechaty`
- After: `wechaty/wechaty`

Thank @YangTe1 for noticing me about this issue, please feel free to let me know if you know there are any other doc posts need to update.

**Comment by IvanEvan** [comment]
This is awsome!
I have a **padplus token**, and want to use **wechaty-python**.
So I followed the steps above to complete the transformation service on my **PC(win10)**.

The Gate Server's log like this:
`            =================================================
            QRCODE_SCAN MSG : 二维码已过期！
            =================================================

10:22:41 INFO IoClient [5]
10:22:42 INFO IoClient [2] http://weixin.qq.com/x/AadpQKtAj44Ynpt7z3dj
10:23:12 VERB PadplusManager setContactAndRoomData() can not proceed due to no cache.
10:23:43 VERB PadplusManager setContactAndRoomData() can not proceed due to no cache.
10:24:13 VERB PadplusManager setContactAndRoomData() can not proceed due to no cache.
10:24:43 VERB PadplusManager setContactAndRoomData() can not proceed due to no cache.
10:25:13 VERB PadplusManager setContactAndRoomData() can not proceed due to no cache.
10:25:43 VERB PadplusManager setContactAndRoomData() can not proceed due to no cache.
10:26:12 VERB PadplusManager setContactAndRoomData() can not proceed due to no cache.
10:26:12 INFO PadplusManager
`
I don't know if I succeeded, But the log info looped.
I tested my token with [https://api.chatie.io/v0/hosties/your_padplus_token](https://api.chatie.io/v0/hosties/your_padplus_token), got the json data:
`{"ip":"219.133.170.253","port":8788}`
I think I made it!

But when I run **ding-dong-bot.py**, an error occurred:
`D:\software\ananconda\envs\py37\python.exe E:/python-wechaty-getting-started-master/examples/ding-dong-bot.py
2020-06-01 17:52:44,876 - Wechaty - INFO - on() listen event <message> with <<function on_message at 0x000001DCF92391F8>>
2020-06-01 17:52:44,876 - Wechaty - INFO - init_puppet_event_bridge() <<wechaty_puppet_hostie.puppet.HostiePuppet object at 0x000001DCFA54F888>>
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(dong) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(error) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(heart-beat) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(ready) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - receive <reset> event <%s>
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(reset) (listenerCount:0) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(friendship) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(login) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(logout) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(message) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-invite) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-join) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-leave) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-topic) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - initPuppetEventBridge() puppet.on(scan) (listenerCount:1) registering...
2020-06-01 17:52:44,877 - Wechaty - INFO - starting ...
Traceback (most recent call last):
  File "E:/python-wechaty-getting-started-master/examples/ding-dong-bot.py", line 64, in <module>
    asyncio.run(main())
  File "D:\software\ananconda\envs\py37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "D:\software\ananconda\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "E:/python-wechaty-getting-started-master/examples/ding-dong-bot.py", line 57, in main
    await bot.start()
  File "D:\software\ananconda\envs\py37\lib\site-packages\wechaty\wechaty.py", line 343, in start
    await self.puppet.start()
  File "D:\software\ananconda\envs\py37\lib\site-packages\wechaty_puppet_hostie\puppet.py", line 694, in start
    await self.puppet_stub.stop()
  File "D:\software\ananconda\envs\py37\lib\site-packages\chatie_grpc\wechaty.py", line 655, in stop
    return await self._unary_unary("/wechaty.Puppet/Stop", request, StopResponse,)
  File "D:\software\ananconda\envs\py37\lib\site-packages\betterproto\__init__.py", line 1018, in _unary_unary
    await stream.send_message(request, end=True)
  File "D:\software\ananconda\envs\py37\lib\site-packages\grpclib\client.py", line 223, in send_message
    await self.send_request()
  File "D:\software\ananconda\envs\py37\lib\site-packages\grpclib\client.py", line 161, in send_request
    protocol = await self._channel.__connect__()
  File "D:\software\ananconda\envs\py37\lib\site-packages\grpclib\client.py", line 635, in __connect__
    self._protocol = await self._create_connection()
  File "D:\software\ananconda\envs\py37\lib\site-packages\grpclib\client.py", line 618, in _create_connection
    ssl=self._ssl,
  File "D:\software\ananconda\envs\py37\lib\asyncio\base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "D:\software\ananconda\envs\py37\lib\asyncio\base_events.py", line 949, in create_connection
    await self.sock_connect(sock, address)
  File "D:\software\ananconda\envs\py37\lib\asyncio\selector_events.py", line 473, in sock_connect
    return await fut
  File "D:\software\ananconda\envs\py37\lib\asyncio\selector_events.py", line 503, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 10060] Connect call failed ('219.133.170.253', 8788)

Process finished with exit code 1`
It seems like network problem, but I'm not sure, because I have deployed a Flask server before in this PC.

So is there any suggest about this error?

> BTW, my wechaty==0.4.12 from pypi

**Comment by huan** [comment]
@IvanEvan Thanks for the reporting!

Please understand that we are in the alpha stage of both the Python Wechaty project and the Token Gate Server, and we might have not enough resources to give feedback in a short period of time.

I'd like to suggest that we'd better try reading the source code from the error message and learn what has happened, it might be the best way to solve the problem for our developers!

At last, the only advice that I can give on your issue is to check whether your IP & Port are public visitable on the internet. (they are showed in the <https://api.chatie.io/v0/hosties/your_padplus_token>) because the last line of the error message is: `TimeoutError: [Errno 10060] Connect call failed`

**Comment by jcai** [comment]
```
10:42:31 VERB EventStreamManager grpcEmit(EVENT_TYPE_MESSAGE[2], {"messageId":"2293744181978686887"})
10:42:32 VERB PuppetServiceImpl messagePayload()
10:42:32 VERB Puppet messagePayload(2293744181978686887)
Error [AssertionError]: Assertion failed
    at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
    at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
    at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
    at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
    at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
    at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
    at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/gene$
ated/wechaty/puppet/message_pb.js:849:12)
```

**Comment by jcai** [comment]
我在开发服务器部署的，是不是开发服务器一直连不上后端的服务器？

`10:50:00 WARN Puppet constructor() watchdog.on(reset) reason: {"data":"","timeout":60000}`

总有这样的消息输出

**Comment by jcai** [comment]
```
10:53:06 VERB Puppet messagePayload(8698359585062855254)                                                                 [17/1897]
Error [AssertionError]: Assertion failed
    at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
    at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
    at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
    at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
    at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
    at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
    at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/gener
ated/wechaty/puppet/message_pb.js:849:12)
    at proto.wechaty.puppet.MessagePayloadResponse.serializeBinary (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/pupp
et/message_pb.js:812:47)
    at serialize_wechaty_puppet_MessagePayloadResponse (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet_grpc_pb.j
s:460:26)
    at sendUnaryResponse (/wechaty/node_modules/grpc/src/server.js:98:15)
    at sendUnaryData (/wechaty/node_modules/grpc/src/server.js:600:9)
    at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-hostie/src/server/puppet-implementation.ts:529:16)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/wechaty-puppet-hostie/dist/src/server/puppet-implementation.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  reportErrorToServer: true,
  messagePattern: 'Assertion failed',
  code: 13
}
```

**Comment by sc180577** [comment]
I can't get it. How to do this on WIN10?

**Comment by bitcrab** [comment]
> @IvanEvan Thanks for the reporting!
> 
> Please understand that we are in the alpha stage of both the Python Wechaty project and the Token Gate Server, and we might have not enough resources to give feedback in a short period of time.
> 
> I'd like to suggest that we'd better try reading the source code from the error message and learn what has happened, it might be the best way to solve the problem for our developers!
> 
> At last, the only advice that I can give on your issue is to **check whether your IP & Port are public visitable on the internet**. (they are showed in the https://api.chatie.io/v0/hosties/your_padplus_token) because the last line of your error message is: **TimeoutError: [Errno 10060] Connect call failed**

I wonder here what's the IP & Port as shown in https://api.chatie.io/v0/hosties/your_padplus_token,like ('219.133.170.253', 8788) refer to? is it the host that has run docker run zixia/wechaty?

**Comment by MrZilinXiao** [comment]
> 客户端发送 `#ding` 消息，服务器会出现下列异常消息。
> 
> ```
> 10:53:06 VERB Puppet messagePayload(8698359585062855254)                                                                 [17/1897]
> Error [AssertionError]: Assertion failed
>     at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
>     at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
>     at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
>     at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
>     at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
>     at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
>     at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/gener
> ated/wechaty/puppet/message_pb.js:849:12)
>     at proto.wechaty.puppet.MessagePayloadResponse.serializeBinary (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/pupp
> et/message_pb.js:812:47)
>     at serialize_wechaty_puppet_MessagePayloadResponse (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet_grpc_pb.j
> s:460:26)
>     at sendUnaryResponse (/wechaty/node_modules/grpc/src/server.js:98:15)
>     at sendUnaryData (/wechaty/node_modules/grpc/src/server.js:600:9)
>     at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-hostie/src/server/puppet-implementation.ts:529:16)
>     at Generator.next (<anonymous>)
>     at fulfilled (/wechaty/node_modules/wechaty-puppet-hostie/dist/src/server/puppet-implementation.js:5:58)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>   reportErrorToServer: true,
>   messagePattern: 'Assertion failed',
>   code: 13
> }
> ```

The same traceback as you received...
<img width="1299" alt="截屏2020-07-02 下午5 38 20" src="https://user-images.githubusercontent.com/42504790/86343325-6473ad00-bc8b-11ea-8778-adb586324c2b.png">

**Comment by echoboss** [comment]
### go-wechaty-getting-started 发送#ding Assertion failed

```
 go run examples/ding-dong-bot.go
Token:  puppet_padplus_******
Endpoint:
2020/07/02 17:53:12 PuppetHostie Start()
2020/07/02 17:53:13 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"http://weixin.qq.com/x/oaBwN7Wob8ZcDVPmqTNT","status":2}})
Scan QR Code to login: ScanStatusWaiting
https://api.qrserver.com/v1/create-qr-code/?data=http://weixin.qq.com/x/oaB*****
2020/07/02 17:53:15 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"http://weixin.qq.com/x/4ehEd3Abadl-muq4DQeJ","status":2}})
Scan QR Code to login: ScanStatusWaiting
https://api.qrserver.com/v1/create-qr-code/?data=http://weixin.qq.com/x/oaB*****
2020/07/02 17:53:15 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"http://weixin.qq.com/x/4ehEd3Abadl-muq4DQeJ","status":2}})
Scan QR Code to login: ScanStatusWaiting
https://api.qrserver.com/v1/create-qr-code/?data=http://weixin.qq.com/x/oaB*****
2020/07/02 17:53:44 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"66cbf343-ab2e-461d-9fb9-c7724ed6e71c","timeout":60000}})
2020/07/02 17:53:44 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"66cbf343-ab2e-461d-9fb9-c7724ed6e71c","timeout":60000}})
2020/07/02 17:53:49 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"","status":3}})
2020/07/02 17:53:49 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"","status":3}})
Scan QR Code to login: ScanStatusScanned
https://api.qrserver.com/v1/create-qr-code/?data=
Scan QR Code to login: ScanStatusScanned
https://api.qrserver.com/v1/create-qr-code/?data=
2020/07/02 17:53:54 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"","status":4}})
2020/07/02 17:53:54 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"","status":4}})
Scan QR Code to login: ScanStatusConfirmed
https://api.qrserver.com/v1/create-qr-code/?data=
Scan QR Code to login: ScanStatusConfirmed
https://api.qrserver.com/v1/create-qr-code/?data=
2020/07/02 17:54:00 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"","timeout":60000}})
2020/07/02 17:54:00 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"","timeout":60000}})
2020/07/02 17:54:00 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_LOGIN payload:{"contactId":"wxid_ymd4vsujsr2522"}})
2020/07/02 17:54:00 PuppetHostie ContactRawPayload(wxid_ym******)
User ***** logined
2020/07/02 17:54:22 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"","timeout":60000}})
2020/07/02 17:54:22 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_MESSAGE payload:{"messageId":"8542867027116486076"}})
2020/07/02 17:54:22 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"","timeout":60000}})
2020/07/02 17:54:22 PuppetHostie MessagePayload(8542867027116486076)
2020/07/02 17:54:22 PuppetHostie onGrpcStreamEvent({type:EVENT_TYPE_MESSAGE payload:{"messageId":"8542867027116486076"}})
2020/07/02 17:54:22 PuppetHostie MessagePayload(8542867027116486076)
2020/07/02 17:54:22 emit message message.Ready() err: rpc error: code = Internal desc = Assertion failed
2020/07/02 17:54:22 emit message message.Ready() err: rpc error: code = Internal desc = Assertion failed
```

**Comment by jcai** [comment]
@echoboss  you can try

```
docker run -e "WECHATY_PUPPET_PADPLUS_TOKEN=puppet_padplus_xxxxxxxxxxx" 
    docker.pkg.github.com/wechaty/scala-wechaty/ding-dong-bot:0.0.16-SNAPSHOT
```

**Comment by landgreenland** [comment]
> ```
> 10:42:31 VERB EventStreamManager grpcEmit(EVENT_TYPE_MESSAGE[2], {"messageId":"2293744181978686887"})
> 10:42:32 VERB PuppetServiceImpl messagePayload()
> 10:42:32 VERB Puppet messagePayload(2293744181978686887)
> Error [AssertionError]: Assertion failed
>     at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
>     at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
>     at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
>     at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
>     at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
>     at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
>     at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/gene$
> ated/wechaty/puppet/message_pb.js:849:12)
> ```

解决了么

**Comment by echoboss** [comment]
> @echoboss you can try
> 
> ```
> docker run -e "WECHATY_PUPPET_PADPLUS_TOKEN=puppet_padplus_xxxxxxxxxxx" 
>     docker.pkg.github.com/wechaty/scala-wechaty/ding-dong-bot:0.0.16-SNAPSHOT
> ```

### 不太行
```
[root@macro ~]# docker pull docker.pkg.github.com/wechaty/scala-wechaty/ding-dong-bot:0.0.16-SNAPSHOT
Error response from daemon: unauthorized: Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['read:packages'], but your token has only been granted the: [''] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
```

**Comment by huan** [comment]
We have a bug with padplus which caused the `timestamp` wrongly to be float instead of an integer:

https://github.com/wechaty/wechaty-puppet-padplus/blob/ab9fa04eacd5b21236690196dbb2a15103333ecf/src/pure-function-helpers/message-raw-payload-parser.ts#L40

Should be fixed as the following:

```diff
-    timestamp : rawPayload.createTime / 1000,   // Padplus message timestamp is seconds
+    timestamp : Math.floow(rawPayload.createTime / 1000),   // Padplus message timestamp is seconds
```

The buggy code set the timestamp to float number like `timestamp: 1593969145.019`, which can not satisfy the Proto Buf.

To be fixed.

**Comment by huan** [comment]
The **Error [AssertionError]: Assertion failed** bug with padplus should be fixed with Wechaty v0.41.26 or later versions.

**Comment by huan** [comment]
There's another bug related to padplus: the `message`, `login`, etc events will be trigger multiple times when using this token gateway.

To be fixed.

**Comment by huan** [comment]
Please use Wechaty@0.41.30 or later version for this token gateway because it fixed the multiple events problem.

**Comment by landgreenland** [comment]
We have fixed the "Error [AssertionError]: Assertion failed" bug for Wechaty Token Gateway. Please upgrade your Wechaty to v0.41.30 or later versions. 

See: https://github.com/wechaty/wechaty/issues/1985#issuecomment-653914544


提问：对应的docker是否也要升级呢？

**Comment by tyowen** [comment]
when i start my bot in go with padpuls token, i got this error
```
PuppetHostie Start() rejection: startGrpcStream err:rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp xxx.xxx.xxx.xxx:8788: connect: connection refused"
```

the port 8788 is accessible from internet. every time i attempt to start the bot in go(lang), here's the log from zixia/wechaty docker container
```
INFO Io on(jsonrpc): [object Object]
VERB Io on(jsonrpc) send({"id":-9007199254740942,"jsonrpc":"2.0","result":8788})
```

**Comment by A2Data** [comment]
020-08-20 15:36:08,647 - Wechaty - INFO - starting puppet ...
2020-08-20 15:36:08,647 - HostiePuppet - INFO - init puppet
2020-08-20 15:36:08,648 - HostiePuppet - INFO - There is no endpoint in cache, trying to fetch endpoint with token.
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda\lib\site-packages\wechaty\wechaty.py", line 417, in start
    await self.puppet.start()
  File "D:\ProgramData\Anaconda\lib\site-packages\wechaty_puppet_hostie\puppet.py", line 862, in start
    self._init_puppet()
  File "D:\ProgramData\Anaconda\lib\site-packages\wechaty_puppet_hostie\puppet.py", line 840, in _init_puppet
    'Your hostie token has no available endpoint, is your token correct?'
wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('Your hostie token has no available endpoint, is your token correct?', None, None)
[Python Wechaty] Ding Dong Bot started.

**Comment by A2Data** [comment]
我也是在 windows10上 使用 exproter设置了 token 但是 读取不到。 

随后在tests/ test_smoke_testing 方法中设置了token
还是错误的。

**Comment by thelosttimes** [comment]
I have a padplus token, and want to use wechaty-python.
So I followed the steps above to complete the transformation service on my PC(CenterOS 7.5).

The Gate Server's log like this:
Online QR Code Image: https://wechaty.js.org/qrcode/https://login.weixin.qq.com/l/QYo8EbsiQA==
03:11:20 INFO IoClient [3] https://login.weixin.qq.com/l/QYo8EbsiQA==]
Online QR Code Image: https://wechaty.js.org/qrcode/https://login.weixin.qq.com/l/QYo8EbsiQA==
03:11:21 WARN PuppetPuppeteerBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com
03:11:23 INFO IoClient [2] https://login.weixin.qq.com/l/gdnjUK9bUg==]
Online QR Code Image: https://wechaty.js.org/qrcode/https://login.weixin.qq.com/l/gdnjUK9bUg==

**Comment by smwsk** [comment]
请问一下padplus 版本更新之后、docker的启动配置要填写、协议改成了export WECHATY_PUPPET=wechaty-puppet-hostie、项目没有办法启动成功

**Comment by huan** [comment]
@smwsk If you are using the Hostie Puppet, then you will be able to use the token directly with Wechaty.

The token gateway is only needed by non-hostie tokens.

**Comment by henryhu712** [comment]
I have a padplus token. How can I just convert the token to be valid without touching my bot code? My bot code is Javascript.

**Comment by huan** [comment]
The PadPlus Puppet Service has been deprecated. Please refer to https://github.com/wechaty/puppet-services/issues/11

You can send an application to replace your padplus token to other types like Donut/WXWork/Rock/PadLocal, lean more about the Puppet Service from https://wechaty.js.org/docs/puppet-services/
