### ISSUE TITLE
为什么我用手机扫码登陆总是失败

### ISSUE THREAD

**Issue by EvynXu** [wechaty/wechaty#2061]
如题，使用最简单 的demo测试也是这样，尝试过好几个账号了，提示如下

为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com

**Comment by WillCup** [comment]
微信官方已经不再支持登陆web协议了。使用ipad协议的把

**Comment by zarte** [comment]
@WillCup  wechaty有ipad协议么？

**Comment by Edward-Zhou** [comment]
@EvynXu 

This is caused by your wechat account could not login through wechat online. 

If you want to use the free `wechaty-puppet-puppeteer`, you will need to use a wechat account which could login wechat online.
otherwise, you will need to apply `wechaty-puppet-padplus`.

@zarte  wechaty support ipadplus protocol, and you could check [Switch Protocol(Puppet)] (https://github.com/wechaty/wechaty#3-switch-protocolpuppet) for supported protocol.

For applying `wechaty-puppet-padplus`, please check [Free Padplus Token](https://github.com/wechaty/wechaty/wiki/Wechaty-Developer-Program#1-free-padplus-token-pad-protocol-wechaty-puppet-padplug)

**Comment by Xuzan9396** [comment]
我有ipad 协议 , qq:594906616,需要联系我

**Comment by huan** [comment]
@Xuzan9396 great to know how have pad protocol.

Would you like to provide it to the community like other Wechaty Puppet service providers? Like https://wechaty.js.org/docs/puppet-services/

Please feel free to contact me if you want to, thanks!
