### ISSUE TITLE
Support   forwarding messages containing binary data

### ISSUE THREAD

**Issue by jcai** [wechaty/wechaty#2093]
If message contains binary data,we can forward message to reduce network traffic and improve performance.

**Comment by huan** [comment]
Yes, we should support forward messages to reduce network traffic and improve performance.

Currently, we have a Puppet Method `messageForward(messageId: string)` implement the forward message logic:

https://github.com/wechaty/wechaty-puppet/blob/3d009a0d1482c78ed945ab983c070e7a4fa4d31b/src/puppet.ts#L935

As the code shows, the current version of the puppet will fetch all the data to local then send them back to the server, which is not efficient.

In order to make it efficient, we need to change the `messageForward` to call the gRPC service and pass the `messageId` to it, so that the forward action can be taken on the server-side.

However, this change might introduce breaking change and we should try our best to prevent it.

 The following steps are a concise design, to be improved:

1. We change the `messageForward` in `Puppet` to be abstract so that it must be implemented by the Puppet Child Class, and also it should be added to our gRPC service, with a new minor version of `wechaty-puppet`.
1. We implemented the `messageForward` in our puppet services with the new `wechaty-puppet` class to support the new gRPC service
1. We upgrade the `wechaty` minor version to include the latest version of the `wechaty-puppet`

Please let me know what you think about it, thanks!

**Comment by Edward-Zhou** [comment]
Is there any roadmap for **We change the messageForward in Puppet to be abstract so that it must be implemented by the Puppet Child Class, and also it should be added to our gRPC service**?

I checked the [puppet.proto](https://github.com/wechaty/grpc/blob/master/proto/wechaty/puppet.proto), there is no defination about `messageForward`.

**Comment by huan** [comment]
@Edward-Zhou we have no roadmap for it but I'd like to accept PR for adding this new feature to our service at any time.

So please feel free to submit a PR to implement it when you want to, thank you very much for your attention.

**Comment by Edward-Zhou** [comment]
For [puppet.proto](https://github.com/wechaty/grpc/blob/master/proto/wechaty/puppet.proto), this is grpc protol defination, is the server implementation opensource? Could you share the server implementation?
I am glad to try if I could make a contribution.

**Comment by huan** [comment]
Yes, the server implementation is open-source.

Here are the links that you might be interested in:

1. Wechaty gRPC npm module(<https://www.npmjs.com/package/@chatie/grpc>) will be auto-generated from the puppet.proto and you can learn how it works by reading the example code at <https://github.com/wechaty/grpc/blob/master/examples/server.ts>
1. Wechaty Puppet Hostie Server implementation source code: https://github.com/wechaty/wechaty-puppet-hostie/blob/master/src/server/puppet-implementation.ts
1. To learn how a puppet implementation works, it's the best way to read the source code of our Wechaty Puppet Mock, which is a testing helper class who implemented the full Puppet interfaces: https://github.com/wechaty/wechaty-puppet-mock/blob/master/src/puppet-mock.ts
