### ISSUE TITLE
 There is no response from the server-side after bumped up to wechaty@0.62.3

### ISSUE THREAD

**Issue by Yat3s** [wechaty/wechaty#2210]
I'm using Donut puppet, and there is an incident today
![image](https://user-images.githubusercontent.com/14801837/125809542-70e639bc-8932-4f09-9396-58a6041d3bb5.png)

And I'm trying to fix it by upgrading to `wechaty@0.62.3`, but it still doesn't work,  there is no any output from the server-side and I don't know what happened...
![image](https://user-images.githubusercontent.com/14801837/125808389-9005b6d7-22bb-4a47-9b47-4000d339883d.png)
I'm sure I tried to remove `package-lock.json` and `node_modules`, and re-install the dependencies again, but it doesn't work...

## 1. Versions

> What is your wechaty version?

Answer: 0.62.3

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: Donut

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: 
```
"wechaty-puppet": "^0.41.1",
"wechaty-puppet-service": "^0.21.8",
```

> What is your node version? (run `node --version`)

Answer: v14.6.0

> What os are you using

Answer: macOS 11.4

**Comment by huan** [comment]
According to https://github.com/Chatie/server/issues/73 our token discover service was downgraded yesterday, and users might have been experiencing issues like yours.

Please retry today and let me know if your problem still exists. If it exists please provide a minimum re-produce repo so that we can investigate the problem for you.

Thank you very much.

**Comment by Yat3s** [comment]
@huan I believe I didn't make any changes but it works again...
Whatever, thanks.

**Comment by Yat3s** [comment]
Closed as resolved
