### ISSUE TITLE
Session Cookies not loaded correctly?

### ISSUE THREAD

**Issue by dax-classix** [wechaty/wechaty#31]
I'm trying to develop using `nodemon`, so my node process is restarting frequently. I wanted to use the `profile` option so I don't need to scan the QR every time it restarts. I am using the sample 7 line script.

I initialize like this:

```
const profile = 'dax.wechaty.json';
const bot = new Wechaty({ profile });
```

I get the following errors upon restart:

```
ERR! PuppetWebBrowser loadSession() addCookies() exception: {"errorMessage":"Can only set Cookies for the current domain","request":{"headers":{"Accept":"application/json; charset=utf-8","Connection":"close","Content-Length":"99","Content-Type":"application/json;charset=UTF-8","Host":"[REDACTED]:65121"},"httpVersion":"1.1","method":"POST","post":"{\"cookie\":{\"name\":\"pgv_si\",\"value\":\"[REDACTED]\",\"path\":\"/\",\"domain\":\".wechat.com\",\"secure\":false}}","url":"/cookie","urlParsed":{"anchor":"","query":"","file":"cookie","directory":"/","path":"/cookie","relative":"/cookie","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/cookie","queryKey":{},"chunks":["cookie"]},"urlOriginal":"/session/[REDACTED]/cookie"}}
```

`[REDACTED]` contains the (seemingly) correct session info.

Am I doing something wrong?

**Comment by zixia** [comment]
Hi dax, 

your code looks no problem at all.

so I suggest you to:

1. run `npm run demo` to have a test with example bot. 
  1. `npm run demo` to start it
  1. it should show login qrcode after a while
  1. scan the qrcode to login
  1. after login, `Ctrl+C` to stop it.
  1. run `npm run demo` again, to see if it could login with the lastest session/cookies.
  1. it should work well.(if you are doing the same as what I just did)
1. otherwise, check the code version you used. What I just tested is the lastest master version.
  1. update by `git pull` to get the lastest code

If you still have problem, please provide more details here.

**Comment by zixia** [comment]
dax, how about this problem going?

I noticed that the domain name is `wechaty.com` in your log. 
> "domain\":\".wechat.com\"

this seems not happen if you did not change the code. wechaty always use `wx.qq.com`, which is hard coded. did you change that?

**Comment by zixia** [comment]
Now we should also consider the new wx.qq.com domain list, i.e.:

1. wx2.qq.com
1. wx8.qq.com

Before we load cookie, maybe we should check the current domain name first: If the current domain name is different to the saved, for example: `wx.qq.com` in saved cookies but the current domain is `wx2.qq.com`, then we save cookies to the current domain `wx2.qq.com` to prevent add cookie failure.

**Comment by zixia** [comment]
```shell
WARN PuppetWebBrowserCookie addCookies() exception: invalid cookie domain: invalid domain:".wx2.qq.com"
  (Session info: chrome=53.0.2785.92)
  (Driver info: chromedriver=2.22 (5e2d5494d735a71aa5c2e7ef9bf5ce96945e92e9),platform=Linux 3.16.0-4-amd64 x86_64)
ERR PuppetWebBrowserCookie load() add() exception: invalid cookie domain: invalid domain:".wx2.qq.com"
  (Session info: chrome=53.0.2785.92)
  (Driver info: chromedriver=2.22 (5e2d5494d735a71aa5c2e7ef9bf5ce96945e92e9),platform=Linux 3.16.0-4-amd64 x86_64)
```

**Comment by dcsan** [comment]
I was also seeing this issue, when trying to extract the minimum files needed to run my own bot.

```
WARN PuppetWebBrowserCookie addCookies() exception: invalid cookie domain: invalid domain:".wechat.com"
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.1 x86_64)
ERR PuppetWebBrowserCookie load() add() exception: invalid cookie domain: invalid domain:".wechat.com"
  (Session info: chrome=54.0.2840.98)
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.1 x86_64)
```

#### Wechaty Doctor

1. Wechaty version: #git[40f47f0 0.6.47]
2. Darwin x64 version 16.1.0 memory 23/8192 MB
3. Docker: false
4. Node version: v7.2.1


This is using the ding-dong example 

it seems fixed in wechaty 0.6.52

#### Wechaty Doctor

1. Wechaty version: #git[4543b8f 0.6.52]
2. Darwin x64 version 16.1.0 memory 230/8192 MB
3. Docker: false
4. Node version: v7.2.1

**Comment by dcsan** [comment]
i still get this error sometimes but doesnt' seem to prevent logging in. 
I think it's related to chrome leaving ghost processes running after exit

**Comment by zixia** [comment]
@dcsan I'm planning to add a method like `PuppetWeb.hostname()` to return the current webwxApp domain, then add the cookie to the right domain name to prevent this error.

Also needed by https://github.com/wechaty/wechaty/issues/121

**Comment by zixia** [comment]
@dcsan @dax-classix the latest code will get `hostname` from `cookie`, then use `hostname` as the wechat web url.

So this issue should be fixed by this commit.
