### ISSUE TITLE
[feature] send login QR by Email/App/ServerChan/...

### ISSUE THREAD

**Issue by dcsan** [wechaty/wechaty#339]
when wechaty is deployed remotely, its difficult to get the QR to login with.

this code snippet below will send the QR code by email, making it easier for anyone to login

```
function handleScan(url, code) {
    if(urls[url]) {
        console.log(`already notified user for ${url}`)
        return
    }
    urls[url] = true
    var config = reload('./config.json')
    if(config.email && config.mailgun) {
        var mg = reload('./mailgun.js')
        if(mg.isValidMailgunConfig(config.mailgun)) {
            /* eslint-disable no-sync */
            var filename = tmp.tmpNameSync({template: '/tmp/qrcode-XXXXXX.jpg'});
            mg.getHttpFile(url, filename, () => mg.email(
                mg.createMailgunClient(config.mailgun),
                mg.createEmailData(config.mailgun, filename, url))
                .then((body) => console.log(body))
                .catch((err) => console.log(err)))
        } else {
            console.log(`invalid configuration ${JSON.stringify(config.mailgun)}`)
        }
    } else {
        console.log('warning: mailgun not configured')
    }
    console.log(`Scan QR Code to login: ${code}\n${url}`)
}

Wechaty.instance()
    .on('scan', handleScan)

```

also this mailgun file to send the image
https://github.com/coderbunker/candobot/blob/master/mailgun.js

source
https://github.com/coderbunker/candobot/blob/master/bot.js#L20-L33

**Comment by ax4** [comment]
Sorry for disappointing! At my first glance, I really love this idea: by adding emailing QR feature, it is more easy for people to login-in any Wechaty instance (especially when it runs on remote)! I would give a hug thumb! 

However, here are three things come to my mind after, and that scared me (I would hope it's only me): 

- **QR code changes faster than email services delay.** QR-login-code, for safety reason and designed by Wechat team, will be dynamically changed. Imagine a worse case: An email could have delay for more than 1 minutes, and QR code changes before the email arrives. Then this person can never get the login processed. He will never get logged-in. 
- **Email may arrive disordered.** Similar to the above case, but more worse: if QR code refreshed, and your last email didn't arrived. But now, a new QR code was sent and arrived immediately. Which QR code you should trust? The early one, or the later one? You can not tell the latest QR. unless you attach the sever time stamp. 
- **Emailing QR could be used by someone to spam.** Of course, I hope this never happens, because I trust every person in the Open Source Community. But in economics, there's a word called 'free-rider', which means they could use our feature without behaving honest! They are liar, but we lowered their cost of cheating (even though, it's just a few lines of code).  

Although emailing will be a good feature, however, I prefer TTY / browser GUI / cached QR image file on server, because that's secured based on the fact: who scan the QR, who is the developer of that Wechaty instance. 

Sincerely, I would help to think a better way, more secured and more real-time than to email the QR.

**Comment by zixia** [comment]
@ax4 long time no see!

@dcsan I also have another idea about how to receive the QRCode: use a App that made for Wechaty. :)

![screenshot_20161211-014540](https://cloud.githubusercontent.com/assets/1361891/24177476/bfdb1eee-0edd-11e7-8f9b-96fa8c3589c6.png)

Please have a look at Google Plus Community at [here](https://plus.google.com/communities/113076295760323769877)

**Comment by lijiarui** [comment]
@dcsan I use [ServerChan](http://sc.ftqq.com/3.version) to send qrcode by wechat OA.

- login with github account to [login](http://sc.ftqq.com/?c=github&a=login), to get a `SCKEY`
- click [here](http://sc.ftqq.com/?c=wechat&a=bind) to bind wechat OA with your wechat by scaning the qrcode
- send `GET request` to http://sc.ftqq.com/SCKEY.send. (I paste my demo code here)

code as follows: 

```
.on('scan', (url, code) => {
  if (!/201|200/.test(String(code))) {
    let loginUrl = url.replace(/\/qrcode\//, '/l/')
    require('qrcode-terminal').generate(loginUrl)
  }
  serverJiang(bot_name+'scan','![logo]('+url+')')
  console.log(`${url}\n[${code}] Scan QR Code in above url to login: `)
})

function serverJiang(username,content){
  var request = require('request')
  var url = 'http://sc.ftqq.com/'+SCKEY+'.send'
  var propertiesObject = {text:username,desp:content}

  request({url:url, qs:propertiesObject}, function (error, response, body) {
    if (!error && response.statusCode == 200) {
      var testjson = JSON.parse(body)
    }
  })
}
```

**Comment by dcsan** [comment]
we do it by slack for now, as its so easy to hook stuff up to. works in china too.
then you can just add people to a slack channel who need to how to login

```
const debug = require('debug')('bot:slackLib');
const request = require('request')

// TODO - move to config file and read from process
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/XXXX"

const slackLib = {
  notify(msg) {

    request({
      method: 'POST',
      uri: SLACK_WEBHOOK_URL,
      json: {
        text: msg
      },
    },
    function(error, response, body) {
      if(error)
      console.log("post to slack", error, response)
    })
  }
};

// slackLib.post("test")

module.exports = exports = slackLib

```

**Comment by ilaipi** [comment]
@lijiarui Hi, I use serverChan as you but I got the qrcode extract error: `QR Code not identified`  

what's the matter?

**Comment by suntong** [comment]
_Hijacking this thread so as to avoid to create yet another issue,_ 

First, a comment -- sending login QR by email is a good idea, for _outside_ China, because I use gmail and my email arrives almost instantaneously. Even for cases that to overcome the server delay or wrong order is necessary, there is still a simple solution -- adding time-stamp as subject prefix, so human can easily tell if the order is wrong, or the message has been long delayed. 

Now my question, how to change the code from
https://blog.chatie.io/guide/2017/01/01/getting-started-wechaty.html
so that I get notified by email when the wechaty session is broken? 
Thus redo the scanning in email will get my bot back in action again (provided that everything is done fast), instead for the script to fail and quit. 

I'm old-fashioned -- I'm on email almost all the time but I only connect my phone online for a short time once a day. 

Thanks

**Comment by lijiarui** [comment]
@ilaipi yes, you are right, QR code can't be extracted(long-tap), it only can be scanned directly by a camera. This is not serverChan's problem, this is wechat mechanism.

**Comment by lijiarui** [comment]
@suntong I feel a little bit confused, what do you mean change the code from https://blog.chatie.io/guide/2017/01/01/getting-started-wechaty.html and why?

**Comment by suntong** [comment]
Oh @lijiarui, let me explain, 

First of all, I have never used ES6/javascript/TypeScript before, but thanks for your code at https://blog.chatie.io/guide/2017/01/01/getting-started-wechaty.html, I'm able to get started easily. Now what I meant change the code, 

- The default behavior of the code is to fail and quit if anything abnormal happens, ref https://github.com/Chatie/wechaty/issues/1059
- However, I want to change it so that, even when the wechaty session is broken, the code can still continue, starting another round that starts with redoing the scanning, showing in console and sends the notification email with QR code as well, so that it will get my bot back in action again. 

Clearer this time?

**Comment by dcsan** [comment]
I believe thats how i had a bot setup. another problem is that it requests multiple QR codes which may also create problems if you dont scan one, endless requests may be a factor in getting a bot banned - although theoretically its just the same as a web browser sitting there waiting to be scanned in...

**Comment by suntong** [comment]
> I believe thats how i had a bot setup.

@dcsan, could you share your code (how you had a bot setup to loop endlessly), or simplify it into a control frames (i.e., without your detailed business logic) so that you can put it into a github gist please?

**Comment by suntong** [comment]
> another problem is that it requests multiple QR codes which may also create problems if you dont scan one, endless requests may be a factor in getting a bot banned

Ok, I'll have that in mind and wait _twice as long_ within _each_ loop.

**Comment by lijiarui** [comment]
@suntong Thanks, pr is welcome.

**Comment by suntong** [comment]
OK, but don't hold your breath, :-) as I have never used ES6/javascript/TypeScript before...

**Comment by lijiarui** [comment]
Have a try :）

**Comment by dcsan** [comment]
@suntong I don't have that to hand really now but you can see above how we called slack. that's about all i've got right now sry

**Comment by suntong** [comment]
thank you @dcsan for your reply, so you meant the code that you included in
https://github.com/Chatie/wechaty/issues/339#issuecomment-289455121, right? 

I don't see any loop in place, are you that that piece of code can resume itself after session is broken.

**Comment by demobo-com** [comment]
I have no problem sending/receiving QRcode. The problem is how to scan the QRcode with one mobile device.

**Comment by lijiarui** [comment]
As I know, this is impossible due to WeChat policy.
