### ISSUE TITLE
Qr Auth fails after a day

### ISSUE THREAD

**Issue by naishstar** [wechaty/wechaty#57]
Hi after 1-2 days our docker instance loses authorisation and we have to rescan a QR code. Is this normal? How long has anyone else kept an account authorised after first scanning a QR code. We were hoping to keep it long running as otherwise we miss messages? Any tips appreciated.

(PS. thanks for a great SDK)

**Comment by naishstar** [comment]
To clarify we successfully scan QR, send and receive messages for around a day and then it stops working , no new messages come in and we can't reply. So have to rescan QR code. It is this we want to minimise so we don't miss messages in the time between losing auth and rescan. Thanks

**Comment by zixia** [comment]
Hi @naishstar ,

Thanks for submit this issue, because `how long will wechaty session keep valid inside browser` is also the same question I want to know.

My suggestion for get the answer, is to:

1. open browser and login wechat by scan qrcode. then monitor it to see how long will wechat keep session for you.
1. find someone work inside tencent, ask them to know the session timeout/management straitegy.
1. find others who use wechaty(or other web wechat framework), we can summary the session time  information to clearify it.

last but not least, there is no guarantee that the web wechat will keep you login at wechat side. you must be prepared for the session lost event.

wechaty will emit `logout` & `scan` event to you, so you can monitor those events, either send email to you to notice, or use other tools like send qrcode to you via wechat message(i.e. via [ServerChan](http://sc.ftqq.com/3.version))

fighting!

**Comment by naishstar** [comment]
Thanks @zixia 

So far we think it is an inactivity timeout killing the sessions by wechat. So providing you have enough activity on a regular basis they should stay open. Our test one was too quiet so we think that caused the issue!

We will keep testing!
