### ISSUE TITLE
Support Friend Request / Contact Add & Del

### ISSUE THREAD

**Issue by kinhunt** [wechaty/wechaty#6]
very cool project.

looking forward to these features:

Deal with friend request
Manage contacts(send friend request/delete contact etc.)

good day

**Comment by zixia** [comment]
thanks! those features are in the roadmap of v0.1.0. I'll push myself to finish this milestone in 1 month. :)

**Comment by sbyinin** [comment]
+1

**Comment by lijiarui** [comment]
+1 
Deal with friend request
Manage contacts

**Comment by zixia** [comment]
@kinhunt @sbyinin delete contact is not possible when we use web api, because `wx.qq.com` has no function to do that.

we had implemented friendrequest feautre( #33 ) and room management feature ( #32 ), we can use them now.

please feel free to submit a issue if you have any problem with the code. thanks.
