### ISSUE TITLE
General Questions.

### ISSUE THREAD

**Issue by sleedata** [wechaty/wechaty#71]
Hi @zixia,

You have save me considerably a lot of time. Thank You for the contribution. Please tag this as a "question" rather than an issue (Can't seem to find the label on github  to associate this with). I'm still in the learning process especially with docker, node, typescript and linux (Coming from c# stack). Here's the following questions I'm hoping you can answer.

1. When we run with docker (i'm using AWS EC2), does it pull the images (or is it container) onto my local workspace?
2. Does this framework relies on 'https://app.wechaty.io/about' (Notice a TOKEN somewhere in the code)?
3. Is https://app.wechaty.io/' a portal in managing the bots ?
  a. Any fees associated with it?
  b. Is it possible for me to look at this site? 
4. Can we shrink the QR code for scan?

**Comment by zixia** [comment]
Hi @sleedata ,

Welcome to the JavaScript world from C#, I love `async` & `await`, it was said that both of them comes from C# and is purposed to ES7 by Microsoft.

according to your questions, please see the following answers:

1. yes. `docker run` will pull the image to local from the Docker hub. so you will not need to download it again when you run `docker run zixia/wechaty` the second time.
2. no for a short answer. wechaty does not rely on `wechaty.io`, and it will not talk to wechaty.io unless you set WECHATY_TOKEN Env Variable.
3. yes. `app.wechaty.io` is designing to be a portal, to scan/check login&logout/restart bot/etc.
  * a. Any willing of payment is welcome. However, I have no idea how to price it so that it will be free from the start.
  * b. Of course, you are welcome to have a shot. It's still in very early design stage, but the code is runnable, you can have a test if you want to.
4. Yes, we can. Go to <https://app.wechaty.io>.

### Howto Use Wechaty with https://app.wechaty.io

1. set TOKEN at wechaty runtime side:  (on your AWS EC2)

  ```shell
  $ alias wechaty='docker run \
    -t -i --rm \
    -e WECHATY_LOG="$WECHATY_LOG" \
    -e WECHATY_TOKEN="$WECHATY_TOKEN" \
    --volume="$(pwd)":/bot \
    --name=wechaty \
    zixia/wechaty \
  '

$ export WECHATY_TOKEN='A-TOKEN-WHAT-EVER-YOU-LIKE'
$ wechaty start
```
2. login app.wechaty.io with your TOKEN

Use your WECHATY_TOKEN as Username and Password, then click "Sign In"

If you are lucky enough, I think you could see your bot status online, include login QR Code, login status, and you can **Shutdown** the bot. 

This portal is still in very early design stage, but the code is runnable and is enough for a demo. 

Please let me know what you think, I'm planning to work on this around next month, any suggestion is welcome, any contribution will be very appreciated. :)

Good luck!

**Comment by sleedata** [comment]
@zixia, I believe the value add is really in the portal. Do you have any architecture artifacts (Class Diagram, Overview Solution Architecture, Sequence Diagram, etc)? I am still learning your code structure, along with your design. If you don't mind sharing, pass along any documentation you may have. I can bring my enterprise skill-sets into the design. We need to consider scalability, exception handling, logging, authentication/authorization, etc... 

If you don't have any of those artifacts, I'll start document it from a diagram perspective... I presume you have Visio?

**Comment by sleedata** [comment]
@zixia, trying out the startup script, got the following error:
'
INFO Client Starting for WECHATY_TOKEN: abcd12345
WARN StateMonitor state.current(online,false) called but there are already in the same state for Io
INFO Wechaty v0.5.1 initializing...
WARN Io initWebSocket() close event[1006: ]
WARN Io reconnect() will reconnect after 0 s
WARN Io initWebSocket() close event[1006: ]
WARN Io reconnect() will reconnect after 0 s

/wechaty/src/wechaty.ts:131
      throw new Error('no user')
            ^
Error: no user
    at Wechaty.user (/wechaty/src/wechaty.ts:131:13)
    at WebSocket.ws.on.e (/wechaty/src/io.ts:221:45)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/wechaty/node_modules/ws/lib/WebSocket.js:841:10)
    at /wechaty/node_modules/ws/lib/Receiver.js:536:18
    at /wechaty/node_modules/ws/lib/Receiver.js:368:7
    at /wechaty/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:361:3)
    at onwrite (_stream_writable.js:352:7)

npm ERR! Linux 4.4.19-29.55.amzn1.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! wechaty@0.5.1 start: `ts-node bin/client`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wechaty@0.5.1 start script 'ts-node bin/client'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wechaty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ts-node bin/client
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wechaty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wechaty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /wechaty/npm-debug.log
'

**Comment by zixia** [comment]
@sleedata Sorry wechaty still has no any architecture artifacts yet, because it's just written from scratch. 

And thank you for your interesting of help with the documentation, I'll very appreciate if you could help, and that will be very useful.

There will be a talk about Wechaty on 11th Dec, I'm invited by another Wechaty developer @Samurais at his Node Party event: <http://www.bagevent.com/event/252533>. You are welcome to join if you have time.

**Comment by zixia** [comment]
@sleedata how about ur research recently? :)

**Comment by zixia** [comment]
I'd like to talk with you when you got any new progress about Wechaty. This issue will be closed, however, contact me via email or wechat is welcome. :)
